#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 80/tcp
sudo chmod a+w /var/www/html/index.nginx-debian.html
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
