#!/usr/bin/env bash
# Bash script that:
#Creates the file /var/run/holbertonscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
file_name="/var/run/holbertonscript.pid"
#sudo touch $file_name
echo $$ > $file_name
while [ 1 ]
do
echo "To infinity and beyond"
trap 'echo "I hate the kill command"; sudo rm $file_name' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'sudo rm $file_name' SIGQUIT
done