#!/usr/bin/env bash
# Bash script to create a file
file_name="/var/run/holbertonscript.pid"
#sudo touch $file_name
echo $$ > $file_name
while [ 1 ]
do
echo "To infinity and beyond"
trap 'echo "I hate the kill command"; sudo rm $file_name' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'sudo rm $file_name' SIGQUIT
done
