#!/usr/bin/env bash
#Run Nginx as Nginx
sudo pkill nginx
sudo ufw allow 8080 
sudo chmod u+r /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo -u nginx service nginx start