#!/usr/bin/env bash
#Run Nginx as Nginx in 7 lines
sudo pkill nginx
sudo chown nginx:nginx /etc/nginx/nginx.conf 
sudo chmod u+r /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx start